export const FLAVORS_SEED = [
  { name: 'Vainilla',   color: '#F3E5AB' },
  { name: 'Chocolate',  color: '#7B3F00' },
  { name: 'Fresa',      color: '#FC8EAC' },
  { name: 'Galleta',    color: '#D2B48C' },
  { name: 'Mandarina',  color: '#F28500' },
  { name: 'Guanábana',  color: '#C8E6C9' },
  { name: 'Limón',      color: '#FFF176' },
  { name: 'Uva',        color: '#7B1FA2' },
  { name: 'Menta',      color: '#A5D6A7' },
  { name: 'Caramelo',   color: '#FFB300' },
];

export const INGREDIENTS_SEED = [
  // ── Ingredientes base para recetas ──────────────────────────────────────────
  { name: 'Helado',                        unit: 'oz',           stockQuantity: 500, minThreshold: 50  },
  { name: 'Banana',                        unit: 'unidad',       stockQuantity: 100, minThreshold: 20  },
  { name: 'Topping de Fresa',              unit: 'oz',           stockQuantity: 1,   minThreshold: 10  },
  { name: 'Topping de Chocolate',          unit: 'oz',           stockQuantity: 3,   minThreshold: 10  },
  { name: 'Topping de Piña',               unit: 'oz',           stockQuantity: 200, minThreshold: 20  },
  { name: 'Topping de Caramelo',           unit: 'oz',           stockQuantity: 200, minThreshold: 20  },
  { name: 'Crema Batida',                  unit: 'unidad',       stockQuantity: 13,  minThreshold: 5   },
  { name: 'Galleta Redonda',               unit: 'unidad',       stockQuantity: 159, minThreshold: 20  },
  { name: 'Galleta Waffle',                unit: 'unidad',       stockQuantity: 100, minThreshold: 10  },
  { name: 'Galleta Molida',                unit: 'cucharada',    stockQuantity: 500, minThreshold: 50  },
  { name: 'Maní / Anicillos',              unit: 'cucharadita',  stockQuantity: 5,   minThreshold: 10  },
  { name: 'Guinda (cereza)',               unit: 'mitad',        stockQuantity: 100, minThreshold: 20  },
  { name: 'Gajos de Melocotón',            unit: 'gajo',         stockQuantity: 2,   minThreshold: 10  },
  { name: 'Sarita Shake 200mL',            unit: 'bolsa',        stockQuantity: 25,  minThreshold: 10  },
  { name: 'Gaseosa 500mL',                 unit: 'botella',      stockQuantity: 19,  minThreshold: 5   },
  { name: 'Cobertura de Chocolate',        unit: 'oz',           stockQuantity: 100, minThreshold: 10  },
  { name: 'Funda Sarita para Conos',       unit: 'unidad',       stockQuantity: 315, minThreshold: 30  },
  { name: 'Canela',                        unit: 'pizca',        stockQuantity: 100, minThreshold: 10  },
  { name: 'Envase 12oz',                   unit: 'unidad',       stockQuantity: 200, minThreshold: 20  },
  { name: 'Envase 9oz',                    unit: 'unidad',       stockQuantity: 200, minThreshold: 20  },
  { name: 'Envase 22oz',                   unit: 'unidad',       stockQuantity: 35,  minThreshold: 10  },
  { name: 'Envase 16oz',                   unit: 'unidad',       stockQuantity: 55,  minThreshold: 10  },
  { name: 'Envase Banana Split',           unit: 'unidad',       stockQuantity: 87,  minThreshold: 10  },
  { name: 'Pajilla',                       unit: 'unidad',       stockQuantity: 500, minThreshold: 50  },
  { name: 'Servilleta',                    unit: 'unidad',       stockQuantity: 500, minThreshold: 50  },
  { name: 'Cucharita',                     unit: 'unidad',       stockQuantity: 500, minThreshold: 50  },
  // ── Del cuaderno de inventario ───────────────────────────────────────────────
  { name: 'Cuchara Bomba',                 unit: 'unidad',       stockQuantity: 25,  minThreshold: 5   },
  { name: 'Porcion de Pastel',             unit: 'unidad',       stockQuantity: 1,   minThreshold: 1   },
  { name: 'Pastel Entero',                 unit: 'unidad',       stockQuantity: 1,   minThreshold: 1   },
  { name: 'Helado 1/2 Galon',             unit: 'unidad',       stockQuantity: 44,  minThreshold: 5   },
  { name: 'Helado Litro',                  unit: 'unidad',       stockQuantity: 28,  minThreshold: 5   },
  { name: 'Helado 1/2 Litro',             unit: 'unidad',       stockQuantity: 10,  minThreshold: 3   },
  { name: 'Jugo de Mango',                 unit: 'unidad',       stockQuantity: 6,   minThreshold: 2   },
  { name: 'Sarita Shake Chocolate 200mL',  unit: 'bolsa',        stockQuantity: 11,  minThreshold: 5   },
  { name: 'Wippeth',                       unit: 'unidad',       stockQuantity: 69,  minThreshold: 10  },
  // ── Paletería y helados empacados ────────────────────────────────────────────
  { name: 'Barritas',                      unit: 'unidad',       stockQuantity: 27,  minThreshold: 10  },
  { name: 'Topolinos',                     unit: 'unidad',       stockQuantity: 56,  minThreshold: 10  },
  { name: 'Palitos',                       unit: 'unidad',       stockQuantity: 23,  minThreshold: 5   },
  { name: 'UFO',                           unit: 'unidad',       stockQuantity: 10,  minThreshold: 3   },
  { name: 'Miniums',                       unit: 'unidad',       stockQuantity: 23,  minThreshold: 5   },
  { name: 'Choconito',                     unit: 'unidad',       stockQuantity: 20,  minThreshold: 5   },
  { name: 'Choco Cremita',                 unit: 'unidad',       stockQuantity: 18,  minThreshold: 5   },
  { name: 'Giga Grande',                   unit: 'unidad',       stockQuantity: 7,   minThreshold: 3   },
  { name: 'Coleccionables',                unit: 'unidad',       stockQuantity: 40,  minThreshold: 10  },
  { name: 'Pachones',                      unit: 'unidad',       stockQuantity: 9,   minThreshold: 3   },
  { name: 'Canastas',                      unit: 'unidad',       stockQuantity: 12,  minThreshold: 3   },
  { name: 'Giga Pequeño',                  unit: 'unidad',       stockQuantity: 7,   minThreshold: 3   },
  { name: 'Caseros',                       unit: 'unidad',       stockQuantity: 18,  minThreshold: 5   },
  { name: 'Cremosa',                       unit: 'unidad',       stockQuantity: 19,  minThreshold: 5   },
  { name: 'Sorby Cremoso',                 unit: 'unidad',       stockQuantity: 18,  minThreshold: 5   },
  { name: 'Sorby Hielo',                   unit: 'unidad',       stockQuantity: 15,  minThreshold: 5   },
  { name: 'Cinta Negra Crispy',            unit: 'unidad',       stockQuantity: 11,  minThreshold: 3   },
  { name: 'Cinta Negra',                   unit: 'unidad',       stockQuantity: 21,  minThreshold: 5   },
  { name: 'Fruta',                         unit: 'unidad',       stockQuantity: 85,  minThreshold: 20  },
  { name: 'Sandra',                        unit: 'unidad',       stockQuantity: 13,  minThreshold: 3   },
  { name: 'Sandwich',                      unit: 'unidad',       stockQuantity: 48,  minThreshold: 10  },
  { name: 'Bananas Congeladas',            unit: 'unidad',       stockQuantity: 10,  minThreshold: 5   },
  // ── Paletería — Copas ────────────────────────────────────────────────────────
  { name: 'Copa Sundae',                   unit: 'unidad',       stockQuantity: 4,   minThreshold: 2   },
  { name: 'Vasitos',                       unit: 'unidad',       stockQuantity: 20,  minThreshold: 5   },
  { name: 'Giga',                          unit: 'unidad',       stockQuantity: 13,  minThreshold: 3   },
  // ── Bebidas ──────────────────────────────────────────────────────────────────
  { name: 'Coca Lata',                     unit: 'unidad',       stockQuantity: 16,  minThreshold: 5   },
  { name: 'Coca Pequeño',                  unit: 'unidad',       stockQuantity: 7,   minThreshold: 3   },
  // ── Envases adicionales ──────────────────────────────────────────────────────
  { name: 'Envase 6oz',                    unit: 'unidad',       stockQuantity: 50,  minThreshold: 10  },
  { name: 'Envase 8oz',                    unit: 'unidad',       stockQuantity: 65,  minThreshold: 10  },
  { name: 'Cajas de Conos',               unit: 'caja',         stockQuantity: 9,   minThreshold: 2   },
];
